---
- name: Install Calico network add-on
  kubernetes.core.k8s:
    src: https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml
    state: present
  when: k8s_installation_network_plugin == 'calico'
  become: true
