---
- name: Check if kubelet already exists
  ansible.builtin.service_facts:
  register: services

- name: Joining control nodes
  ansible.builtin.command: "{{ hostvars[groups['control_nodes'][0]].control_join_command.stdout }}"
  register: joining_control
  changed_when: joining_control.rc == 0
  become: true
  when: ansible_facts.services["kubelet.service"].state != "running"
