---
- name: Preparation of the nodes
  ansible.builtin.include_tasks: prepare_nodes.yml

- name: Installation of the applications on the nodes
  ansible.builtin.include_tasks: install_applications.yml
