---
- name: Preparation of the nodes
  ansible.builtin.include_tasks: prepare-nodes.yml
  when: inventory_hostname in groups["control-nodes"] or inventory_hostname in groups["worker-nodes"]

- name: Installation of the applications on the nodes
  ansible.builtin.include_tasks: install-applications-debian.yml
  when: ansible_os_family == 'Debian' and inventory_hostname in groups["control-nodes"] or inventory_hostname in groups["worker-nodes"]

- name: Installation of the applications on the nodes
  ansible.builtin.include_tasks: install-applications-rhel.yml
  when: ansible_os_family == 'RedHat' and inventory_hostname in groups["control-nodes"] or inventory_hostname in groups["worker-nodes"]

- name: Initialising cluster
  ansible.builtin.include_tasks: cluster-init.yml
  when: inventory_hostname == groups["control-nodes"][0]

- name: Deploy network plugin
  ansible.builtin.include_tasks: deploy-calico.yml
  when: inventory_hostname == groups["control-nodes"][0]

- name: Join control nodes to cluster
  ansible.builtin.include_tasks: join-control-nodes.yml
  when: inventory_hostname in groups["control-nodes"]

- name: Join worker nodes to cluster
  ansible.builtin.include_tasks: join-worker-nodes.yml
  when: inventory_hostname in groups["worker-nodes"]
