---
- name: Creating keepalived config
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Reload service for keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true
  become: true
