---
- name: Creating keepalived config
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  with_items:
    - peer: "{{ hostvars.groups.proxy_nodes[1].ansible_facts.ip }}"

- name: Reload service for keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true
